version: '3.9'

services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: nest-api
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      # Use the service name "mongo" as hostname inside the compose network
      MONGO_URI: mongodb://root:example@mongo:27017/?authSource=admin
    ports:
      - '3000:3000'
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  mongo_data:
